
- hosts: all
  tasks:
    - name: Enable EPEL Repository on CentOS 8
      become: true    
      become_method: sudo
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
      dnf:
        name: epel-release
        state: latest
    
    - name: Enable EPEL Repository on CentOS 7
      become: true    
      become_method: sudo
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
      yum:
        name: epel-release
        state: latest
        
    
    
    - name: Install nginx
      become: true
      become_method: sudo
      yum:
        name: nginx
        state: present

    - name: Create directories nginx conf
      become: true
      become_method: sudo
      file:
        path: "/etc/nginx/{{item}}"
        owner: root
        group: root
        mode: 0755
        recurse: yes
        state: directory
      with_items: ["sites-available", "sites-enabled"]
    

    - name: Copy file with owner and permissions
      become: true
      become_method: sudo
      copy:
        src: /root/upeu-ssl
        dest: /root/tls
        owner: root
        group: root
        mode: '0644'