
- hosts: all
  tasks:
    - name: Enable EPEL Repository on CentOS 8
      become: true    
      become_method: sudo
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
      dnf:
        name: epel-release
        state: latest
    
    - name: Enable EPEL Repository on CentOS 7
      become: true    
      become_method: sudo
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
      yum:
        name: epel-release
        state: latest

    - name: Install nginx
      become: true
      become_method: sudo
      yum:
        name: nginx
        state: present
    
    - name: Enable service Nginx, and not touch the state
      become: true
      become_method: sudo
      service:
        name: nginx
        enabled: yes
    
    - name: Start service nginx, if not started
      become: true
      become_method: sudo
      service:
        name: nginx
        state: started
    
    - name: Verifica que existe nginx.conf
      become: true
      become_method: sudo
      stat: path=/etc/nginx/nginx.conf
      register: nginx_conf
    
    - name: Save Nignx Conf
      become: true
      become_method: sudo
      command: mv /etc/nginx/nginx.conf etc/nginx/nginx.conf_back
      when: nginx_conf.stat.exists

    - name: Copy Nginx COnf and permissions
      become: true
      become_method: sudo
      copy:
        src: /root/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0755


    - name: Create directories nginx conf
      become: true
      become_method: sudo
      with_items: ["sites-available", "sites-enabled"]
      file:
        path: "/etc/nginx/{{item}}"
        owner: root
        group: root
        mode: 0755
        recurse: yes
        state: directory
      
    

    - name: Copy file with owner and permissions
      become: true
      become_method: sudo
      copy:
        src: /root/upeu-ssl
        dest: /root/tls
        owner: root
        group: root
        mode: '0644'