- hosts: all

  tasks:
    - name: Remove hosts 
      become: true
      become_method: sudo
      file: 
        path: /etc/nginx/sites-enabled/html1.conf
        state: absent

    - name: Restart Nginx, if not started
      when: "'nginx' in ansible_facts.packages"
      become: true
      become_method: sudo
      service:
        name: nginx
        state: restarted
        