- hosts: all

  tasks:
    - name: rm link
      shell: sudo rm /etc/nginx/sites_enabled/html1.conf
  
    - name: add Link
      shell: sudo ln -s /etc/nginx/sites_available/html2.conf /etc/nginx/sites_enabled/

    - name: "Check if packages is installed"
      package_facts:
      manager: "auto"

    - name: Restart Nginx, if not started
      when: "'nginx' in ansible_facts.packages"
      
      service:
        name: nginx
        state: restarted