- hosts: all

  tasks:
    - name: Remove hosts 
      become: true
      become_method: sudo
      file: 
        path: /etc/nginx/sites-enabled/html1.conf
        state: absent

    - file:
        src: /etc/nginx/sites-available/html2.conf
        dest: /etc/nginx/sites-enabled/html2.conf
        owner: root
        group: root
        state: link

    - name: Restart Nginx, if not started
      become: true
      become_method: sudo
      service:
        name: nginx
        state: restarted
        