- hosts: all

  tasks:
    - name: Copy file with owner and permissions
      become: true
      become_method: sudo
      copy:
        src: /root/upeu-ssl2020
        dest: /root/tls
        owner: root
        group: root
        mode: '0644'
    
    - name: Copy file with owner and permissions
      become: true
      become_method: sudo
      copy:
        src: /root/upeu-ssl2021
        dest: /root/tls
        owner: root
        group: root
        mode: '0644'
  
    
    - name: Before Ansible 2.3, option 'dest', 'destfile' or 'name' was used instead of 'path'
      replace:
          path: /etc/nginx/sites-available
          regexp: '^/root/tls/upeu-ssl2020/'
          replace: '/root/tls/upeu-ssl2021/'


    - name: "Check if packages is installed"
      package_facts:
        manager: "auto"

    - name: Restart Nginx, if not started
      when: "'nginx' in ansible_facts.packages"
      become: true
      become_method: sudo
      service:
        name: nginx
        state: restarted
        